# Compare the models based on elpd.

library(rstan)
library(tidyverse)
library(loo)

# number of folds in the cv, fixed to 10 here
K <- 10

# function to combine the samples generated by different folds, written for the full data
# the objects should be named following pattern <model_name>_<fold_number>_data1.rds
# the function takes as an argument the model_name part
combine_lls <- function(name) {
  # the log-likelihoods
  lls <- readRDS(paste0("", name, "_", 1, "data1.rds"))
  
  # combine the different folds
  for (i in 2:K) {
    ll <- readRDS(paste0("", name, "_", i, "data1.rds"))
    
    lls <- cbind(lls, ll)
  }
  return(lls)
}

# function to combine the samples generated by different folds, written for the main data
# the objects should be named following pattern <model_name>_<fold_number>_data2.rds
# the function takes as an argument the model_name part
combine_lls_data2 <- function(name) {
  # the log-likelihoods
  lls <- readRDS(paste0("", name, "_", 1, "_data2.rds"))
  
  # combine the different folds
  for (i in 2:K) {
    ll <- readRDS(paste0("", name, "_", i, "_data2.rds"))
    
    lls <- cbind(lls, ll)
  }
  return(lls)
}

# combine the samples
bnp <- combine_lls("log_pd_bin_nophi")
bp <- combine_lls("log_pd_bin_phi")
bbnp <- combine_lls("log_pd_beta_bin_nophi")
bbp <- combine_lls("log_pd_beta_bin_phi")
bnp2 <- combine_lls_data2("log_pd_bin_nophi")
bp2 <- combine_lls_data2("log_pd_bin_phi")
bbnp2 <- combine_lls_data2("log_pd_beta_bin_nophi")
bbp2 <- combine_lls_data2("log_pd_beta_bin_phi")

# get the elpds
(elpd_kfold_bnp <- elpd(bnp))
(elpd_kfold_bp <- elpd(bp))
(elpd_kfold_bbnp <- elpd(bbnp))
(elpd_kfold_bbp <- elpd(bbp))
(elpd_kfold_bnp2 <- elpd(bnp2))
(elpd_kfold_bp2 <- elpd(bp2))
(elpd_kfold_bbnp2 <- elpd(bbnp2))
(elpd_kfold_bbp2 <- elpd(bbp2))

# compare different models
loo_compare(elpd_kfold_bnp, elpd_kfold_bp, elpd_kfold_bbnp, elpd_kfold_bbp,
            elpd_kfold_bnp2, elpd_kfold_bp2, elpd_kfold_bbnp2, elpd_kfold_bbp2)

